name: SUSHI
channels:
  - rusty1s
  - pytorch-lts
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - bottleneck=1.3.4=py38hce1f21e_0
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py38h497a2fe_1001
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.4.26=h06a4308_0
  - certifi=2021.10.8=py38h06a4308_2
  - cffi=1.14.6=py38ha65f79e_0
  - chardet=4.0.0=py38h578d9bd_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cloudpickle=1.6.0=py_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=3.4.7=py38ha5dfef3_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.10.0=py38_0
  - cytoolz=0.11.0=py38h7b6447c_0
  - dask-core=2021.8.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=py_0
  - expat=2.4.1=h2531618_2
  - ffmpeg=4.2.2=h20bf706_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=h5ab3b9f_0
  - fsspec=2021.7.0=pyhd3eb1b0_0
  - glib=2.69.0=h5202010_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - googledrivedownloader=0.4=pyhd3deb0d_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - imageio=2.9.0=pyhd3eb1b0_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - jinja2=3.0.1=pyhd8ed1ab_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.3.1=py38h2531618_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libblas=3.9.0=11_linux64_mkl
  - libcblas=3.9.0=11_linux64_mkl
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=h14aa051_19
  - libgfortran4=7.5.0=h14aa051_19
  - libgomp=9.3.0=h5101ec6_17
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=11_linux64_mkl
  - libllvm11=11.1.0=h3826bc1_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - locket=0.2.1=py38h06a4308_1
  - lz4-c=1.9.3=h295c915_1
  - markupsafe=2.0.1=py38h497a2fe_0
  - matplotlib=3.4.2=py38h06a4308_0
  - matplotlib-base=3.4.2=py38hab158f2_0
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.0=py38h42c9631_2
  - mkl_random=1.2.2=py38h51133e4_0
  - munkres=1.1.4=py_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.6.2=pyhd8ed1ab_0
  - ninja=1.10.2=hff7bd54_1
  - numexpr=2.7.3=py38h22e1b3c_1
  - numpy=1.20.3=py38hf144106_0
  - numpy-base=1.20.3=py38h74d4b33_0
  - olefile=0.46=py_0
  - openh264=2.1.0=hd408876_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1n=h7f8727e_0
  - packaging=21.0=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pillow=8.3.1=py38h2c7a002_0
  - pip=21.0.1=py38h06a4308_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - pysocks=1.7.1=py38h578d9bd_3
  - python=3.8.11=h12debd9_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-louvain=0.15=pyhd3deb0d_0
  - python_abi=3.8=2_cp38
  - pytorch=1.8.2=py3.8_cuda10.2_cudnn7.6.5_0
  - pytorch-cluster=1.5.9=py38_torch_1.8.0_cu102
  - pytorch-geometric=1.7.2=py38_torch_1.8.0_cu102
  - pytorch-scatter=2.0.8=py38_torch_1.8.0_cu102
  - pytorch-sparse=0.6.11=py38_torch_1.8.0_cu102
  - pytorch-spline-conv=1.2.1=py38_torch_1.8.0_cu102
  - pytz=2021.1=pyhd8ed1ab_0
  - pywavelets=1.1.1=py38h7b6447c_2
  - pyyaml=5.4.1=py38h497a2fe_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - requests=2.27.1=pyhd3eb1b0_0
  - scikit-image=0.18.1=py38ha9443f7_0
  - scikit-learn=0.24.2=py38ha9443f7_0
  - scipy=1.7.1=py38h292c36d_2
  - setuptools=52.0.0=py38h06a4308_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tbb=2021.5.0=hd09550d_0
  - threadpoolctl=2.2.0=pyh8a188c0_0
  - tifffile=2020.10.1=py38hdd07704_2
  - tk=8.6.10=hbc83047_0
  - toolz=0.11.1=pyhd3eb1b0_0
  - torchaudio=0.8.2=py38
  - torchvision=0.9.2=py38_cu102
  - tornado=6.1=py38h27cfd23_0
  - typing_extensions=3.10.0.0=pyh06a4308_0
  - urllib3=1.26.6=pyhd8ed1ab_0
  - wheel=0.37.0=pyhd3eb1b0_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==0.13.0
    - aiohttp==3.7.4.post0
    - async-timeout==3.0.1
    - attrs==21.2.0
    - beautifulsoup4==4.11.1
    - cachetools==4.2.2
    - docopt==0.6.2
    - easydict==1.10
    - faiss-gpu==1.7.2
    - filelock==3.8.0
    - flake8==3.9.2
    - flake8-import-order==0.18.1
    - future==0.18.2
    - gdown==4.5.1
    - gitdb==4.0.7
    - gitpython==3.1.18
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.5
    - grpcio==1.39.0
    - idna==3.2
    - importlib-metadata==4.12.0
    - iniconfig==1.1.1
    - jsonpickle==1.5.2
    - lapsolver==1.1.0
    - llvmlite==0.39.0
    - markdown==3.3.4
    - mccabe==0.6.1
    - motmetrics==1.2.0
    - multidict==5.1.0
    - munch==2.5.0
    - oauthlib==3.1.1
    - opencv-python==4.5.3.56
    - pandas==1.3.2
    - pluggy==0.13.1
    - prettytable==3.4.1
    - protobuf==3.17.3
    - pulp==2.1
    - py==1.10.0
    - py-cpuinfo==8.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.7.0
    - pydeprecate==0.3.1
    - pyflakes==2.3.1
    - pytest==6.2.4
    - pytest-benchmark==3.4.1
    - pytorch-lightning==1.4.2
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - sacred==0.8.2
    - seaborn==0.11.2
    - smmap==4.0.0
    - soupsieve==2.3.2.post1
    - tabulate==0.9.0
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - termcolor==2.0.1
    - toml==0.10.2
    - torchmetrics==0.5.0
    - tqdm==4.62.1
    - wcwidth==0.2.5
    - werkzeug==2.0.1
    - wrapt==1.12.1
    - xmltodict==0.12.0
    - yacs==0.1.8
    - yarl==1.6.3
    - zipp==3.8.1
